-- Repara acentos dañados (solo filas con caracteres corruptos)
update categories set title='Tortellonis', note='docena' where id='tortellonis' and (title ~ '[√¬]' or note ~ '[√¬]');
update products set name='Jamón Serrano y Rúcula', description='Jamón serrano curado y rúcula fresca' where category_id='tortellonis' and sort=0 and (name ~ '[√¬]' or description ~ '[√¬]');
update products set name='4 Quesos', description='Mezcla cremosa de cuatro quesos' where category_id='tortellonis' and sort=1 and (name ~ '[√¬]' or description ~ '[√¬]');
update categories set title='Varenikes', note='docena' where id='varenikes' and (title ~ '[√¬]' or note ~ '[√¬]');
update products set name='Papa & Cebolla', description='Puré de papa y cebolla salteada' where category_id='varenikes' and sort=0 and (name ~ '[√¬]' or description ~ '[√¬]');
update categories set title='Sorrentinos', note='docena' where id='sorrentinos' and (title ~ '[√¬]' or note ~ '[√¬]');
update products set name='Jamón & Queso', description='Clásico jamón cocido y queso' where category_id='sorrentinos' and sort=0 and (name ~ '[√¬]' or description ~ '[√¬]');
update products set name='Calabaza & Mozzarella', description='Calabaza asada y mozzarella' where category_id='sorrentinos' and sort=1 and (name ~ '[√¬]' or description ~ '[√¬]');
update products set name='Salmón Rosado', description='Masa negra rellena de salmón rosado' where category_id='sorrentinos' and sort=2 and (name ~ '[√¬]' or description ~ '[√¬]');
update products set name='Wok de Verdura', description='Verduras salteadas estilo wok' where category_id='sorrentinos' and sort=3 and (name ~ '[√¬]' or description ~ '[√¬]');
update categories set title='Ravioles', note='2 planchas' where id='ravioles' and (title ~ '[√¬]' or note ~ '[√¬]');
update products set name='Verdura', description='Espinaca, acelga y ricota' where category_id='ravioles' and sort=0 and (name ~ '[√¬]' or description ~ '[√¬]');
update products set name='Pollo al Verdeo', description='Pollo desmenuzado y cebolla de verdeo' where category_id='ravioles' and sort=1 and (name ~ '[√¬]' or description ~ '[√¬]');
update categories set title='Panzottis', note='docena' where id='panzottis' and (title ~ '[√¬]' or note ~ '[√¬]');
update products set name='Hongos & Panceta Ahumada', description='Hongos salteados y panceta ahumada' where category_id='panzottis' and sort=0 and (name ~ '[√¬]' or description ~ '[√¬]');
update categories set title='Tovotellis', note='docena' where id='tovotellis' and (title ~ '[√¬]' or note ~ '[√¬]');
update products set name='Vacío Braseado a la Cerveza', description='Vacío braseado lento a la cerveza' where category_id='tovotellis' and sort=0 and (name ~ '[√¬]' or description ~ '[√¬]');
update products set name='Mejillones al Ajillo', description='Mejillones salteados al ajillo' where category_id='tovotellis' and sort=1 and (name ~ '[√¬]' or description ~ '[√¬]');
update products set name='Bondiola', description='Bondiola braseada a fuego lento' where category_id='tovotellis' and sort=2 and (name ~ '[√¬]' or description ~ '[√¬]');
update categories set title='Canelones', note='4 unidades' where id='canelones' and (title ~ '[√¬]' or note ~ '[√¬]');
update products set name='Verdura', description='Espinaca, acelga y ricota' where category_id='canelones' and sort=0 and (name ~ '[√¬]' or description ~ '[√¬]');
update products set name='Seso & Verdura', description='Relleno de seso y verdura, en masa de espinaca' where category_id='canelones' and sort=1 and (name ~ '[√¬]' or description ~ '[√¬]');
update categories set title='Raviolones', note='docena' where id='raviolones' and (title ~ '[√¬]' or note ~ '[√¬]');
update products set name='Cordero Braseado', description='Cordero braseado a fuego lento' where category_id='raviolones' and sort=0 and (name ~ '[√¬]' or description ~ '[√¬]');
update products set name='Palta & Langostinos', description='Palta cremosa y langostinos salteados' where category_id='raviolones' and sort=1 and (name ~ '[√¬]' or description ~ '[√¬]');
update products set name='Berenjena y Tomates S.', description='Berenjena y tomates secos' where category_id='raviolones' and sort=2 and (name ~ '[√¬]' or description ~ '[√¬]');
update categories set title='Fideos', note='500grs' where id='fideos' and (title ~ '[√¬]' or note ~ '[√¬]');
update products set name='Spaghettis al Huevo', description='Masa fresca al huevo' where category_id='fideos' and sort=0 and (name ~ '[√¬]' or description ~ '[√¬]');
update products set name='Tagliatelles de Espinaca', description='Cinta fresca de espinaca' where category_id='fideos' and sort=1 and (name ~ '[√¬]' or description ~ '[√¬]');
update products set name='Spaghetti Nero di Sepia', description='Masa fresca teñida con tinta de sepia' where category_id='fideos' and sort=2 and (name ~ '[√¬]' or description ~ '[√¬]');
update categories set title='Ñoquis', note='500grs' where id='noquis' and (title ~ '[√¬]' or note ~ '[√¬]');
update products set name='Ñoquis de Papa', description='Receta clásica de papa' where category_id='noquis' and sort=0 and (name ~ '[√¬]' or description ~ '[√¬]');
update products set name='Malfattis de Espinaca', description='Espinaca y ricota' where category_id='noquis' and sort=1 and (name ~ '[√¬]' or description ~ '[√¬]');
update categories set title='FranKids', note='30 unidades mini' where id='frankids' and (title ~ '[√¬]' or note ~ '[√¬]');
update products set name='Raviolines de Calabaza', description='Mini raviolines de calabaza' where category_id='frankids' and sort=0 and (name ~ '[√¬]' or description ~ '[√¬]');
update categories set title='Empanadas', note='docena' where id='empanadas' and (title ~ '[√¬]' or note ~ '[√¬]');
update products set name='Criolla de Carne', description='Receta criolla clásica de carne cortada a cuchillo' where category_id='empanadas' and sort=0 and (name ~ '[√¬]' or description ~ '[√¬]');
update products set name='Batata y Boniato', description='Batata y boniato' where category_id='empanadas' and sort=1 and (name ~ '[√¬]' or description ~ '[√¬]');
update categories set title='Salsas & Extras', note='sumalas a cualquier pedido' where id='salsas' and (title ~ '[√¬]' or note ~ '[√¬]');
update products set name='Filetto' where category_id='salsas' and sort=0 and name ~ '[√¬]';
update products set name='Bolognesa' where category_id='salsas' and sort=1 and name ~ '[√¬]';
update products set name='Mixta' where category_id='salsas' and sort=2 and name ~ '[√¬]';
update products set name='4 Quesos' where category_id='salsas' and sort=3 and name ~ '[√¬]';
update products set name='Verdeo' where category_id='salsas' and sort=4 and name ~ '[√¬]';
update products set name='Mostaza' where category_id='salsas' and sort=5 and name ~ '[√¬]';
update products set name='Roquefort' where category_id='salsas' and sort=6 and name ~ '[√¬]';
update products set name='Salsa Blanca' where category_id='salsas' and sort=7 and name ~ '[√¬]';
update products set name='Champignones' where category_id='salsas' and sort=8 and name ~ '[√¬]';
update products set name='Crema de Hongos' where category_id='salsas' and sort=9 and name ~ '[√¬]';
update products set name='Camarones (crema)' where category_id='salsas' and sort=10 and name ~ '[√¬]';
